version: '3.8'
services:
  redis:
    container_name: chat-bh
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

#  r2db:
#    image: redislabs/redisearch:latest
#    container_name: r2db
#    ports:
#      - "6380:6380"
#    volumes:
#      - ./data:/data

volumes:
  redis-data:
