version: '3.8'
services:
  redis:
    container_name: chat-bh
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  mongodb:
    container_name: chat-bh-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

volumes:
  redis-data:
  mongodb-data:
